@startuml PaquetesConCasosDeUsoYRelaciones

actor Admin

package "Administración" {
    usecase "CU017: Importación datos" as UC019
    usecase "CU018: Gestión roles" as UC020
}

Admin --> UC019
Admin --> UC020

@enduml