// <auto-generated />
using System;
using METDAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace METDAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501143242_BeforePlayerUpload3")]
    partial class BeforePlayerUpload3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("METCore.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PlayerId", "Active")
                        .IsUnique()
                        .HasFilter("[Active] = 1");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("METCore.Models.ContractYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<double>("Earned")
                        .HasColumnType("float");

                    b.Property<double>("GaranteedMoney")
                        .HasColumnType("float");

                    b.Property<double?>("Incentives")
                        .HasColumnType("float");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractYears");
                });

            modelBuilder.Entity("METCore.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abb")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Mascot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasDiscriminator().HasValue("Franchise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("METCore.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("Position2")
                        .HasColumnType("int");

                    b.Property<int?>("Position3")
                        .HasColumnType("int");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("METCore.Models.SeasonStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Att")
                        .HasColumnType("int");

                    b.Property<int?>("Car")
                        .HasColumnType("int");

                    b.Property<int?>("Cmp")
                        .HasColumnType("int");

                    b.Property<int>("FantPt")
                        .HasColumnType("int");

                    b.Property<int>("Fmb")
                        .HasColumnType("int");

                    b.Property<int>("FmbRec")
                        .HasColumnType("int");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<int?>("Int")
                        .HasColumnType("int");

                    b.Property<int?>("OvrRank")
                        .HasColumnType("int");

                    b.Property<int?>("PassTD")
                        .HasColumnType("int");

                    b.Property<int?>("PassYards")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PosRank")
                        .HasColumnType("int");

                    b.Property<int?>("Rec")
                        .HasColumnType("int");

                    b.Property<int?>("RecTD")
                        .HasColumnType("int");

                    b.Property<int?>("RecYards")
                        .HasColumnType("int");

                    b.Property<int?>("RushTD")
                        .HasColumnType("int");

                    b.Property<int?>("RushYards")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int?>("Tgt")
                        .HasColumnType("int");

                    b.Property<int>("VBD")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PlayerId", "Season")
                        .IsUnique();

                    b.ToTable("SeasonStats");
                });

            modelBuilder.Entity("METCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Tlf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("METCore.Models.Team", b =>
                {
                    b.HasBaseType("METCore.Models.Franchise");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Team");
                });

            modelBuilder.Entity("METCore.Models.Contract", b =>
                {
                    b.HasOne("METCore.Models.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("METCore.Models.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("METCore.Models.ContractYear", b =>
                {
                    b.HasOne("METCore.Models.Contract", "Contract")
                        .WithMany("ContractYears")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("METCore.Models.Player", b =>
                {
                    b.HasOne("METCore.Models.Franchise", null)
                        .WithMany("Players")
                        .HasForeignKey("FranchiseId");
                });

            modelBuilder.Entity("METCore.Models.SeasonStats", b =>
                {
                    b.HasOne("METCore.Models.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("METCore.Models.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("METCore.Models.Team", b =>
                {
                    b.HasOne("METCore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("METCore.Models.Contract", b =>
                {
                    b.Navigation("ContractYears");
                });

            modelBuilder.Entity("METCore.Models.Franchise", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("METCore.Models.Player", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
