// <auto-generated />
using System;
using METDAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace METDAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521194948_Guaranteed")]
    partial class Guaranteed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("METCore.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<long>("Guaranteed")
                        .HasColumnType("bigint");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<int>("YearSigned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PlayerId", "Active")
                        .IsUnique()
                        .HasFilter("[Active] = 1");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("METCore.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mascot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasDiscriminator().HasValue("Franchise");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("METCore.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("Position2")
                        .HasColumnType("int");

                    b.Property<int?>("Position3")
                        .HasColumnType("int");

                    b.Property<bool>("Retired")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("METCore.Models.SeasonStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FGStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("IntStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("KOStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("KRStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("PRStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("PassStatsId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PuntStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("RecStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("RushStatsId")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int?>("TackleStatsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FGStatsId");

                    b.HasIndex("IntStatsId");

                    b.HasIndex("KOStatsId");

                    b.HasIndex("KRStatsId");

                    b.HasIndex("PRStatsId");

                    b.HasIndex("PassStatsId");

                    b.HasIndex("PuntStatsId");

                    b.HasIndex("RecStatsId");

                    b.HasIndex("RushStatsId");

                    b.HasIndex("TackleStatsId");

                    b.HasIndex("PlayerId", "Season")
                        .IsUnique();

                    b.ToTable("SeasonStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.FGStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Blk")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<int>("LongAtt")
                        .HasColumnType("int");

                    b.Property<int>("LongMade")
                        .HasColumnType("int");

                    b.Property<int>("MidAtt")
                        .HasColumnType("int");

                    b.Property<int>("MidMade")
                        .HasColumnType("int");

                    b.Property<int>("ShAtt")
                        .HasColumnType("int");

                    b.Property<int>("ShMade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FGStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.IntStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.KOStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kick")
                        .HasColumnType("int");

                    b.Property<int>("OOB")
                        .HasColumnType("int");

                    b.Property<int>("OnSide")
                        .HasColumnType("int");

                    b.Property<int>("OnSideRec")
                        .HasColumnType("int");

                    b.Property<int>("Ret")
                        .HasColumnType("int");

                    b.Property<int>("RetYds")
                        .HasColumnType("int");

                    b.Property<int>("TB")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KOStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.KRStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FC")
                        .HasColumnType("int");

                    b.Property<int>("Fmb")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<int>("Plus20")
                        .HasColumnType("int");

                    b.Property<int>("Plus40")
                        .HasColumnType("int");

                    b.Property<int>("Ret")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KRStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.PRStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FC")
                        .HasColumnType("int");

                    b.Property<int>("Fmb")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<int>("Plus20")
                        .HasColumnType("int");

                    b.Property<int>("Plus40")
                        .HasColumnType("int");

                    b.Property<int>("Ret")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PRStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.PassStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Att")
                        .HasColumnType("int");

                    b.Property<int>("Cmp")
                        .HasColumnType("int");

                    b.Property<int>("INT")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<double>("PR")
                        .HasColumnType("float");

                    b.Property<int>("Plus20")
                        .HasColumnType("int");

                    b.Property<int>("Plus40")
                        .HasColumnType("int");

                    b.Property<int>("Reach1st")
                        .HasColumnType("int");

                    b.Property<int>("Sck")
                        .HasColumnType("int");

                    b.Property<int>("SckYds")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PassStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.PuntStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Blk")
                        .HasColumnType("int");

                    b.Property<int>("Down")
                        .HasColumnType("int");

                    b.Property<int>("FC")
                        .HasColumnType("int");

                    b.Property<int>("Inside20")
                        .HasColumnType("int");

                    b.Property<int>("Kick")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<int>("OOB")
                        .HasColumnType("int");

                    b.Property<int>("Ret")
                        .HasColumnType("int");

                    b.Property<int>("RetYds")
                        .HasColumnType("int");

                    b.Property<int>("TB")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PuntStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.RecStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Att")
                        .HasColumnType("int");

                    b.Property<int>("Fmb")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<int>("Plus20")
                        .HasColumnType("int");

                    b.Property<int>("Plus40")
                        .HasColumnType("int");

                    b.Property<int>("Reach1st")
                        .HasColumnType("int");

                    b.Property<int>("Rec")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("YAC")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.RushStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Att")
                        .HasColumnType("int");

                    b.Property<int>("Fmb")
                        .HasColumnType("int");

                    b.Property<int>("Lng")
                        .HasColumnType("int");

                    b.Property<int>("Plus20")
                        .HasColumnType("int");

                    b.Property<int>("Plus40")
                        .HasColumnType("int");

                    b.Property<int>("Reach1st")
                        .HasColumnType("int");

                    b.Property<int>("TD")
                        .HasColumnType("int");

                    b.Property<int>("Yds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RushStats");
                });

            modelBuilder.Entity("METCore.Models.Stats.TackleStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Asst")
                        .HasColumnType("int");

                    b.Property<int>("Comb")
                        .HasColumnType("int");

                    b.Property<double>("Sck")
                        .HasColumnType("float");

                    b.Property<int>("Solo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TackleStats");
                });

            modelBuilder.Entity("METCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Tlf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("METCore.Models.Team", b =>
                {
                    b.HasBaseType("METCore.Models.Franchise");

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Team");
                });

            modelBuilder.Entity("METCore.Models.Contract", b =>
                {
                    b.HasOne("METCore.Models.Franchise", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("METCore.Models.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("METCore.Models.Player", b =>
                {
                    b.HasOne("METCore.Models.Franchise", null)
                        .WithMany("Players")
                        .HasForeignKey("FranchiseId");
                });

            modelBuilder.Entity("METCore.Models.SeasonStats", b =>
                {
                    b.HasOne("METCore.Models.Stats.FGStats", "FGStats")
                        .WithMany()
                        .HasForeignKey("FGStatsId");

                    b.HasOne("METCore.Models.Stats.IntStats", "IntStats")
                        .WithMany()
                        .HasForeignKey("IntStatsId");

                    b.HasOne("METCore.Models.Stats.KOStats", "KOStats")
                        .WithMany()
                        .HasForeignKey("KOStatsId");

                    b.HasOne("METCore.Models.Stats.KRStats", "KRStats")
                        .WithMany()
                        .HasForeignKey("KRStatsId");

                    b.HasOne("METCore.Models.Stats.PRStats", "PRStats")
                        .WithMany()
                        .HasForeignKey("PRStatsId");

                    b.HasOne("METCore.Models.Stats.PassStats", "PassStats")
                        .WithMany()
                        .HasForeignKey("PassStatsId");

                    b.HasOne("METCore.Models.Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("METCore.Models.Stats.PuntStats", "PuntStats")
                        .WithMany()
                        .HasForeignKey("PuntStatsId");

                    b.HasOne("METCore.Models.Stats.RecStats", "RecStats")
                        .WithMany()
                        .HasForeignKey("RecStatsId");

                    b.HasOne("METCore.Models.Stats.RushStats", "RushStats")
                        .WithMany()
                        .HasForeignKey("RushStatsId");

                    b.HasOne("METCore.Models.Stats.TackleStats", "TackleStats")
                        .WithMany()
                        .HasForeignKey("TackleStatsId");

                    b.Navigation("FGStats");

                    b.Navigation("IntStats");

                    b.Navigation("KOStats");

                    b.Navigation("KRStats");

                    b.Navigation("PRStats");

                    b.Navigation("PassStats");

                    b.Navigation("Player");

                    b.Navigation("PuntStats");

                    b.Navigation("RecStats");

                    b.Navigation("RushStats");

                    b.Navigation("TackleStats");
                });

            modelBuilder.Entity("METCore.Models.Team", b =>
                {
                    b.HasOne("METCore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("METCore.Models.Franchise", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("METCore.Models.Player", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
