@startuml DiagramaSecuencia_CU004
!theme plain

actor "Actor Usuario" as usuario
participant "IC_Auth" as interfaz
participant "G_Auth" as gestion
collections "Users" as users

usuario -> interfaz : 1. solicitarModificarCredenciales()

activate interfaz
interfaz -> gestion : 2. U1 := getUsuario(username)
activate gestion
gestion -> users : 3. U1 := getUsuario(username)
gestion <-- users : 4. U1
interfaz <-- gestion : 5. U1
deactivate gestion

loop U2 IS NOT NULL
    loop Antigua contraseña incorrecta
        loop Datos inválidos
            usuario <- interfaz : 6. modificarCredenciales := solicitarDatos()
            deactivate interfaz
            activate usuario
            usuario --> interfaz : 7. modificarCredenciales
            deactivate usuario
            activate interfaz
            
            interfaz -> interfaz : 8. validarDatos(credenciales)
        end
    
        interfaz -> gestion : 9. validarCredenciales(credenciales)
        deactivate interfaz
        activate gestion
        gestion -> gestion : 10. validarCredenciales(credenciales)

        gestion --> interfaz : 11. error
        interfaz --> usuario : 12. mostrarError("Contraseña actual incorrecta")
    end

    gestion -> users : 13. U2 := getUsuario(nuevoUsername)
    activate users
    users --> gestion : 14. U2
    deactivate users
    gestion --> interfaz : 15. error
    interfaz --> usuario : 16. mostrarError("El nombre de usuario ya está en uso")
end

gestion -> users : 17. actualizarCredenciales(credenciales)
users --> gestion : 18. ok
deactivate users
gestion --> interfaz : 19. ok
deactivate gestion
activate interfaz
interfaz -> interfaz : 20. cerrarSesion()
interfaz --> usuario : 21. redirigirInicioSesion()
deactivate interfaz

note right of usuario : El actor puede cancelar\nel proceso en cualquier momento

@enduml