@startuml DiagramaSecuencia_CU008
!theme plain

actor "Actor Usuario" as usuario
participant "IC_Teams" as interfaz
participant "G_Teams" as gestion
collections "Teams" as teams

usuario -> interfaz : 1. duplicarEquipo(equipoId)

activate interfaz
interfaz -> gestion : 2. E1 := getEquipo(equipoId)
activate gestion
gestion -> teams : 3. E1 := getEquipoPorId(equipoId)
activate teams
teams --> gestion : 4. E1
deactivate teams

alt E1 IS NULL
    gestion --> interfaz : 5. error
    interfaz --> usuario : 6. mostrarError("El equipo no existe")
    deactivate interfaz
end

gestion -> gestion : 7. E2 := duplicarEquipo(E1)
gestion -> teams : 8. E2 := crearEquipo(E2)
activate teams
teams --> gestion : 9. E2
deactivate teams
gestion --> interfaz : 10. E2
deactivate gestion
interfaz --> usuario :11. E2
deactivate interfaz

note right of usuario : El actor puede cancelar\nel proceso en cualquier momento

@enduml