@startuml DiagramaSecuencia_CU005
!theme plain

actor "Actor Usuario" as usuario
participant "IC_Auth" as interfaz
participant "G_Auth" as gestion
collections "Users" as users
collections "Teams" as teams

usuario -> interfaz : 1. bajaUsuario()
activate interfaz

interfaz -> gestion : 2. eliminarUsuario(username)
activate gestion

gestion -> teams : 3. *eliminarEquiposDeUsuario(username)
activate teams
teams --> gestion : 6. ok
deactivate teams

gestion -> users : 7. eliminarUsuario(username)
activate users
users --> gestion : 8. ok
deactivate users

gestion --> interfaz : 9. ok
deactivate gestion

interfaz -> interfaz : 10. cerrarSesion()
interfaz --> usuario : 11. redirigeAInicio()
deactivate interfaz

note right of usuario : El actor puede cancelar\nel proceso en cualquier momento

@enduml