@startuml DiagramaSecuencia_CU001
!theme plain

actor "Actor Anónimo" as anonimo
participant "IC_Auth" as interfaz
participant "G_Auth" as gestion
collections "Users" as users

anonimo -> interfaz : 1. solicitarRegistro()
activate interfaz

loop Datos inválidos OR usuario existe
    loop Datos inválidos
        anonimo <- interfaz : 2. nuevoUsuario := solicitarDatos()
        deactivate interfaz
        activate anonimo
        anonimo --> interfaz : 3. nuevoUsuario
        deactivate anonimo
        
        interfaz -> interfaz : 4. validarDatos(nuevoUsuario)
        activate interfaz
    end
    
    interfaz -> gestion : 5. U1 := buscarUsuario(nuevoUsuario)
    deactivate interfaz
    activate gestion
    gestion -> users : 6. U1 := buscarUsuario(nuevoUsuario)
    activate users
    users --> gestion : 7. U1
    deactivate users

    alt U1 IS NOT NULL
        gestion --> interfaz : 8. U1
        interfaz --> anonimo : 9. mostrarError("Usuario ya existe")
    end
end

gestion -> users : 10. U2 := crearUsuario(nuevoUsuario)
activate users
users --> gestion : 11. U2
deactivate users
gestion --> interfaz : 12. U2
deactivate gestion
interfaz --> anonimo : 13. confirmarRegistro(U2)
deactivate interfaz

note right of anonimo : El actor puede cancelar\nel proceso en cualquier momento

@enduml