@startuml DiagramaSecuencia_CU002
!theme plain

actor "Actor Anónimo" as anonimo
participant "IC_Auth" as interfaz
participant "G_Auth" as gestion
collections "Users" as users

anonimo -> interfaz : 1. solicitarInicioSesion()
activate interfaz

loop usuario no existe
    loop Credenciales inválidas
        anonimo <- interfaz : 2. credenciales := solicitarCredenciales()
        deactivate interfaz
        activate anonimo
        anonimo --> interfaz : 3. credenciales
        deactivate anonimo
        activate interfaz
        
        interfaz -> interfaz : 4. validarDatos(credenciales)
    end
    
    interfaz -> gestion : 5. U1 := autenticarUsuario(credenciales)
    deactivate interfaz
    activate gestion
    gestion -> users : 6. U1 := *buscarPorCredenciales(credenciales)
    activate users
    users --> gestion : 7. U1
    deactivate users

    gestion --> interfaz : 8. null
    interfaz --> anonimo : 9. mostrarError("Usuario no registrado")
end


gestion --> interfaz : 10. usuario
deactivate gestion
interfaz --> anonimo : 11. permitirAcceso(usuario)
deactivate interfaz

note right of anonimo : El actor puede cancelar\nel proceso en cualquier momento

@enduml