@startuml DiagramaSecuencia_CU007
!theme plain

actor "Actor Usuario" as usuario
participant "IC_Teams" as interfaz
participant "G_Teams" as gestion
collections "Teams" as teams

usuario -> interfaz : 1. solicitarModificarEquipo(equipoId)

activate interfaz
interfaz -> gestion : 2. E1 := obtenerEquipo(equipoId)
activate gestion
gestion -> teams : 3. E1 := buscarPorId(equipoId)
activate teams
teams --> gestion : 4. E1
deactivate teams

alt E1 IS NULL OR E1.propietario != usuario
    gestion --> interfaz : 5. error
    interfaz --> usuario : 6. mostrarError("No es propietario")
end    

gestion --> interfaz : 7. E1
deactivate gestion

loop Datos incompletos o inválidos
    usuario <-- interfaz : 8. editarEquipo(E1)
    deactivate interfaz
    activate usuario
    usuario --> interfaz : 9. cambios
    deactivate usuario
    activate interfaz
    interfaz -> interfaz : 10. validarDatos(cambios)
end
    
interfaz -> gestion : 11. actualizarEquipo(E1, cambios)
activate gestion
gestion -> teams : 12. actualizarEquipo(E1, cambios)
activate teams
teams --> gestion : 13. ok
deactivate teams
gestion --> interfaz : 14. ok
deactivate gestion
interfaz --> usuario : 15. ok
deactivate interfaz


note right of usuario : El actor puede cancelar\nel proceso en cualquier momento

@enduml