@startuml DiagramaSecuencia_CU006
!theme plain

actor "Actor Usuario" as usuario
participant "IC_Teams" as interfaz
participant "G_Teams" as gestion
collections "Teams" as teams

usuario -> interfaz : 1. crearEquipo()
activate interfaz

loop Datos inválidos o incompletos
    usuario <- interfaz : 2. equipo := solicitarDatos()
    deactivate interfaz
    activate usuario
    usuario --> interfaz : 3. equipo
    deactivate usuario
    activate interfaz
    
    interfaz -> interfaz : 4. validarDatos(equipo)
    usuario <-- interfaz : 5. mostrarError("Datos inválidos o incompletos")
    
end

interfaz -> gestion : 5. crearEquipo(datosEquipo)
activate gestion
gestion -> teams : 10. T1 := crearEquipo(datosEquipo)
teams --> gestion : 11. T1
gestion --> interfaz : 12. T1
deactivate gestion
interfaz --> usuario : 13. ok
deactivate interfaz

note right of usuario : El actor puede cancelar\nel proceso en cualquier momento

@enduml