<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\Team\RosterSettingsDto.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Diagramas\DiagramaDeClases_Final.png" />
    <None Remove="Diagramas\DiagramaDeClases_Inicial.png" />
    <None Remove="Diagramas\DiagramaDePaquetes_ConCUs.png" />
    <None Remove="Diagramas\DiagramaDePaquetes_ConRelaciones.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU001.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU002.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU003.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU004.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU005.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU006.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU007.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU008.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU009.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU010.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU011.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU012.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU013.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU014.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU015.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU016.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU017.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU018.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU019.png" />
    <None Remove="Diagramas\DiagramaSecuencia_CU020.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.12.1" />
    <PackageReference Include="PlantUml.Net" Version="1.4.80" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
  </ItemGroup>

</Project>