@startuml DiagramaSecuencia_CU003
!theme plain

actor "Actor Usuario" as usuario
participant "IUSistema" as interfaz

usuario -> interfaz : 1. solicitarCerrarSesion()

activate interfaz
interfaz -> interfaz : 2. cerrarSesion()
interfaz --> usuario : 3. redireccionAInicio()
deactivate interfaz

@enduml